Algoritmo DATOS_DE_ESTUDIANTE
	Definir NOMBRE COMO TEXTO;
	DEFINIR CALIFICACION COMO REAL;
	Escribir "INGRESA NOMBRE";
	LEER  NOMBRE;
	ESCRIBIR "INGRES CALIFICACION";
	LEER CALIFICACION;
	Si CALIFICACION >8 Entonces
	 ESCRIBIR "FELICIDADES";
	SiNo 
		ESCRIBIR "NOS VEMOS EN R1 ";
	FinSi 

		
	
	
	
	
	
	
	
	
FinAlgoritmo
